### ISSUE TITLE
Directory and file purging logic

### ISSUE THREAD

**Issue by rofe** [adobe/helix-purge#128]
`helix-purge` should handle directories and files as follows:

Inner CDN:
- Surrogate key purge
- also `content-proxy` cache: `https://${branch}--${repo}--${owner}.hlx.page/${pathPrefix}.md`

Outer CDN:
- `/`: directory, also purge `/index` and `/index.html`
- `/index`: also purge `/` and '/index.html`
- `/index.html`: also purge `/` and '/index`
- `/foo.html`: also purge `/foo`
- `/foo`: also purge `/foo.html`
- `/bar.json`: only purge `/bar.json`

and report all purged URLs in the response.

cc @tripodsan @trieloff

**Comment by trieloff** [comment]
> /: directory, also purge `/index` and `/index.html`

Nominally, we still have configurable directory indexes.

At least for the inner CDN, we should consider an additional option: 

https://github.com/adobe/helix-shared/blob/278244ce50e8aec4b0df035ab627544f147d12c7/src/utils.js#L62-L80

extend this function to calculate the normalized URL (no query params, no extension, no selectors) and append the surrogate key of that to the calculated value. This way we'd also be able to purge the `md` file that belongs to the `html`

**Comment by rofe** [comment]
> Nominally, we still have configurable directory indexes.

I think we should keep it simple for now and stick with `index` - until somebody complains 😉
