### ISSUE TITLE
Surrogate key purging

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-purge#4]
#2 @rofe 

> Nice! But...
> 
> > Try https://adobeioruntime.net/api/v1/web/helix/helix-services/purge@ci?host=theblog--adobe.hlx.page&xfh=blog.adobe.com&path=/en/2020/08/14/6-ways-ta-adapt-advance-your-business-during-pandemic.html
> 
> ... obviously in the case of theblog it's not so simple, because the paths differ between inner and outer CDN... it would be cool if instead of the `path` parameter, one could alternatively specify a surrogate key. This way we could also use this service to bust all cached index json segments at once.
> 
> We could then create a "Purge cache" bookmarklet, similar to the "Preview" one, which calculates the surrogate key from the URL of the source document.

**Comment by davidnuescheler** [comment]
instead of calculating it, it should take it from the sourcehash that's in the `<meta name="x-source-hash" content="{hash-here}">`

**Comment by tripodsan** [comment]
no, the source hash is **NOT** the surrogate key. you get the surrogate key, by looking a the `x-source-location` header can computing the hmac_sha256 of it:

```
$ echo -n '/drives/b!PpnkewKFAEaDTS6slvlVjh_3ih9lhEZMgYWwps6bPIWZMmLU5xGqS4uES8kIQZbH/items/01DJQLOWZ2NO76OI7TOZAJNCZQUFLF6I3T' | hmac256 --binary helix | base64 | cut -c 1-16
5b1ugAW6HiKkp39r
```

**Comment by trieloff** [comment]
the other complication in @rofe's plan is that we do not have the outer cdn's id or token, but need it to purge by surrogate key.

**Comment by tripodsan** [comment]
> the other complication in @rofe's plan is that we do not have the outer cdn's id or token, but need it to purge by surrogate key.

yes, we do. using `helix-cache-flush` which uses the `helix-bot-config.yaml` stored in the repository to figure out the outer CDN service config (and purge token). Of course this only works, as long as we have access to it.
