### ISSUE TITLE
Static ok.html contains reference to branch `include-drives`

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-purge#50]
https://github.com/adobe/helix-purge/blob/0e6c8e965065665e06ed0f83e8373e5685c0f6ae/ok.html#L10

**Comment by tripodsan** [comment]
this came in through @davidnuescheler 's PR:

https://github.com/adobe/helix-purge/pull/47/files

I thought this was intentional.

**Comment by dominique-pfister** [comment]
Hm, but the check for equality (bar the sourcehash) in `stop.js` didn't change:

https://github.com/adobe/helix-purge/blob/0e6c8e965065665e06ed0f83e8373e5685c0f6ae/src/stop.js#L22-L25

and this fails at the moment.

**Comment by rofe** [comment]
See also https://github.com/adobe/helix-purge/pull/47#pullrequestreview-523989116 😉

**Comment by rofe** [comment]
If we would check `/OK.plain.html` we wouldn't have this problem...
