### ISSUE TITLE
Emergency stop switch: check plain html rendition

### ISSUE THREAD

**Issue by rofe** [adobe/helix-purge#53]
The "dead man switch" that blocks purging when something is wrong with Helix Pages currently checks the full rendition of `OK.md` against a static copy. This includes metadata tags with GH branches exposed in the URLs. This was the reason for a regression (see #50) and might cause further issues in the future.

Checking against a plain html rendition instead (`/OK.plain.html`) would be more streamlined, branch-safe and require less frequent updates of the static copy.

**Comment by tripodsan** [comment]
but it doesn't check so many resources, like the esi included head
